language: go

go:
  - 1.3

install:
  - go get github.com/Clever/csvlint/cmd/csvlint

script:
  - csvlint election2011/benchmark-relative.csv && csvlint election2011/benchmark-absolute.csv
  - csvlint data.csv && csvlint all-polls.csv

notifications:
  email:
    on_success: change
    on_failure: always
