language: ruby

rvm:
  - 1.9.3

install:
  - gem install csvlint

script:
  - csvlint election2011/benchmark-relative.csv && csvlint election2011/benchmark-absolute.csv
  - csvlint data.csv && csvlint all-polls.csv

notifications:
  email:
    on_success: change
    on_failure: always
